language: ruby
sudo: required
services:
- docker
bundler_args: "--without system_tests"
script:
- gem install bundler
- bundle install --path vendor/bundle
- bundle exec rake
matrix:
  include:
  - rvm: 2.1.8
    env: PUPPET_VERSION="~> 3.0" BEAKER_set="docker-centos6"
  - rvm: default
    env: PUPPET_VERSION="~> 4.0" BEAKER_set="docker-centos6-pc1"
  - rvm: 2.1.8
    env: PUPPET_VERSION="~> 3.0" BEAKER_set="docker-centos7"
  - rvm: default
    env: PUPPET_VERSION="~> 4.0" BEAKER_set="docker-centos7-pc1" DEPLOY_TO_FORGE=yes
deploy:
  provider: puppetforge
  user: tsystemsmms
  password:
    secure: ZeD67Wgiq7d6U9PFWAfaDzE++2wp74RfJScXrZemzGSL2EdlRakEan/gwrg7hyYOGqNmnRDm2x5jMYx4uJrDcN4GNaoVowUF0Yw95owphZQ7F5VT+IIwAxWOg9ro4hHBgbAXDSNCaDqXezb8WGnKFOcLFSi+dJ5HXHQQ/mFaZpuRKtr/CWeqviK8C7VI3iiTfzf8uawmNbKjwTdhzlTlc8v2VcW+4XGCr6uq5gQbBHbgwYJnO0WwtNAa4GgVU7NpT62qgatpZO1ZYgiJly8C0Wgd29hH+/8RXmdAKgjtrHtftwB3oQ8Te6Gaxv/y/pOxBGtw9A307MXQ0ThBcywSWv7Pkk+CqZgNTJRM2kiIb6JcjDtzsG6zKDsNkGxgHySLJ58m1t+l3smyZTvtfrTBKh8Z3tzx2h1bBLtFPxg5Qy+0iS2gX0jwmRF91G24ytbQJ5Wic9NoVuk4YLzX7f/SR5Dk0/eKnDz5WDrPHl6TYl438wYY4D5Oxn90GiQZXED3tXgalB0zoxuYyNJUrbUXHMm/dyQSr/u24XOWqQQaLldPgaUXVnKrBpEKojQIdBYGY117MVqCAt4fG9pVayGuBOHhvWZiqwOwevHfZLnO7ow6jt7cEWT5oN7sYw8V/wJh00gFI+gaaGCzfCxp1QdhlZGb7vrfreLJruWF2NuGZT0=
  on:
    tags: true
    all_branches: true
    condition: "$DEPLOY_TO_FORGE = yes"
